name: digital_ot_toolbox
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  pdf: ^3.11.3
  intl: ^0.20.2
  flutter_screenutil: ^5.9.3
  printing: ^5.14.2
  share_plus: ^12.0.1
  fl_chart: ^0.68.0  # âœ… (ØªÙ… Ø§Ù„Ù†Ù‚Ù„ Ø¥Ù„Ù‰ Ù‡Ù†Ø§)
  image_picker: ^1.0.7       # ðŸ†• Ù„Ø§Ø®ØªÙŠØ§Ø± Ø§Ù„ØµÙˆØ±
  permission_handler: ^11.3.0 # ðŸ†• Ù„Ø¥Ø¯Ø§Ø±Ø© Ø§Ù„Ø£Ø°ÙˆÙ†Ø§Øª (Android/iOS)
  url_launcher: ^6.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/NotoSansArabic-Regular.ttf 
    - assets/fonts/NotoColorEmoji-Regular.ttf
  fonts:
    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf